import type {
  DeliveryStatus,
  DeliveryType,
  EmailAddressStatus,
  OutputMode,
  RecordCreatorType,
  SummaryFormat,
  TranscriptSource,
  UsageEventType,
  UsageUnit,
  VideoPlatform,
  VideoRecordStatus,
} from "./schema.js";

export type UserProfileRow = {
  /** User profile primary key. Matches `auth.users.id`. */
  id: string;
  /** Display email copied from Supabase Auth for convenient reads. */
  email: string | null;
  /** Billing or access plan identifier, such as free, pro, or admin. */
  plan: string;
  /** Time when the profile row was created. */
  createdAt: Date;
  /** Time when the profile row was last updated. */
  updatedAt: Date;
};

export type VideoRecordRow = {
  /** Video record primary key. Used by detail pages and queue payloads as recordId. */
  id: string;
  /** Owner user id from Supabase Auth. Used for RLS and resource ownership checks. */
  userId: string;
  /** Original video URL submitted by the user or agent. */
  sourceUrl: string;
  /** Normalized video URL used for duplicate detection and search. */
  normalizedUrl: string;
  /** Source platform for the submitted video. */
  platform: VideoPlatform;
  /** Video title fetched by the worker during metadata extraction. */
  title: string | null;
  /** Video author, channel, or Bilibili creator name. */
  author: string | null;
  /** Video duration in seconds. */
  durationSeconds: number | null;
  /** Video thumbnail URL fetched from the source platform. */
  thumbnailUrl: string | null;
  /** Current processing status shown in records, detail pages, and agent status queries. */
  status: VideoRecordStatus;
  /** Final transcript source chosen for this record, if transcript extraction has succeeded. */
  transcriptSource: TranscriptSource | null;
  /** Requested output mode for this task. */
  outputMode: OutputMode;
  /** Whether the worker may fall back to audio extraction and ASR when subtitles are unavailable. */
  fallbackToAudio: boolean;
  /** Whether this task should send the summary to the user's default verified email. */
  sendEmail: boolean;
  /** Source that created this record, such as web UI, MCP agent, system, or scheduled job. */
  createdByType: RecordCreatorType;
  /** Creator identifier. For MCP records this can be the token id; for web records this can be the user id. */
  createdById: string | null;
  /** Structured failure code used for recovery actions and UI messaging. */
  errorCode: string | null;
  /** Human-readable failure message for users or operations debugging. */
  errorMessage: string | null;
  /** Time when the record was created. */
  createdAt: Date;
  /** Time when the record was last updated. */
  updatedAt: Date;
  /** Time when processing completed, failed, or was cancelled. */
  completedAt: Date | null;
  /** Soft delete timestamp. Null means the record is visible. */
  deletedAt: Date | null;
};

export type TranscriptRow = {
  /** Transcript result primary key. */
  id: string;
  /** Related video record id. */
  recordId: string;
  /** Owner user id from Supabase Auth. */
  userId: string;
  /** Transcript language, such as zh-CN or en. */
  language: string | null;
  /** Transcript source, such as manual subtitle, auto subtitle, or ASR. */
  source: TranscriptSource;
  /** Full transcript text stored directly in Postgres for MVP. */
  plainText: string | null;
  /** Object storage key for large transcript payloads or subtitle files. */
  storageKey: string | null;
  /** Number of segment rows associated with this transcript. */
  segmentCount: number;
  /** Time when the transcript was created. */
  createdAt: Date;
};

export type TranscriptSegmentRow = {
  /** Transcript segment primary key. */
  id: string;
  /** Parent transcript id. */
  transcriptId: string;
  /** Related video record id, duplicated for fast record detail reads. */
  recordId: string;
  /** Owner user id from Supabase Auth, duplicated for RLS and filtering. */
  userId: string;
  /** Segment start time in seconds. May include decimals. */
  startSeconds: number | null;
  /** Segment end time in seconds. May include decimals. */
  endSeconds: number | null;
  /** Text spoken or shown during this segment. */
  text: string;
  /** Stable ordering value for transcript display. */
  sortOrder: number;
};

export type SummaryRow = {
  /** Summary result primary key. */
  id: string;
  /** Related video record id. */
  recordId: string;
  /** Owner user id from Supabase Auth. */
  userId: string;
  /** Summary language, defaulting to zh-CN. */
  language: string;
  /** Summary format, such as brief, detailed, or email digest. */
  format: SummaryFormat;
  /** Summary title generated by the model or copied from the video title. */
  title: string | null;
  /** Short overview shown in record detail and compact previews. */
  shortSummary: string | null;
  /** Structured key points generated from the transcript. */
  keyPoints: unknown[];
  /** Structured timeline items generated from the transcript. */
  timeline: unknown[];
  /** Structured takeaways or action items. */
  takeaways: unknown[];
  /** Full Markdown summary used for copy, email, and export. */
  markdown: string | null;
  /** Model name used to generate the summary. */
  model: string | null;
  /** Prompt version used to generate the summary. */
  promptVersion: string | null;
  /** Time when the summary was created. */
  createdAt: Date;
};

export type EmailAddressRow = {
  /** Email address primary key. Used by delivery tools as toEmailId. */
  id: string;
  /** Owner user id from Supabase Auth. */
  userId: string;
  /** Recipient email address. */
  email: string;
  /** Verification state for this recipient address. */
  status: EmailAddressStatus;
  /** Whether this is the user's default recipient email. */
  isDefault: boolean;
  /** Hash of the verification token. The raw token is never persisted. */
  verificationTokenHash: string | null;
  /** Time when the latest verification email was sent. */
  verificationSentAt: Date | null;
  /** Time when the email address was verified. */
  verifiedAt: Date | null;
  /** Time when a digest email was last sent successfully to this address. */
  lastSentAt: Date | null;
  /** Time when the email address row was created. */
  createdAt: Date;
};

export type DeliveryRecordRow = {
  /** Delivery record primary key. */
  id: string;
  /** Related video record id. */
  recordId: string;
  /** Owner user id from Supabase Auth. */
  userId: string;
  /** Summary version used for this delivery. Null if the summary was deleted. */
  summaryId: string | null;
  /** Delivery target type, such as email or webhook. */
  type: DeliveryType;
  /** Delivery target id. For email delivery this points to `email_addresses.id`. */
  targetId: string;
  /** Delivery lifecycle status. */
  status: DeliveryStatus;
  /** Email subject or webhook event title. */
  subject: string | null;
  /** Failure message when delivery fails. */
  errorMessage: string | null;
  /** Time when the delivery record was created. */
  createdAt: Date;
  /** Time when the delivery was sent successfully. */
  sentAt: Date | null;
};

export type McpTokenRow = {
  /** MCP token primary key. Can be used as an agent actor id. */
  id: string;
  /** Owner user id from Supabase Auth. */
  userId: string;
  /** Human-readable token name shown in settings. */
  name: string;
  /** Display prefix used to identify the token without exposing the secret. */
  tokenPrefix: string;
  /** Hash of the token secret. The raw token is never persisted. */
  tokenHash: string;
  /** Scope list that controls which MCP tools this token may call. */
  scopes: string[];
  /** Token expiration time. Null means no explicit expiration. */
  expiresAt: Date | null;
  /** Time when the token was last used successfully. */
  lastUsedAt: Date | null;
  /** Time when the token was revoked. Null means the token is active. */
  revokedAt: Date | null;
  /** Time when the token was created. */
  createdAt: Date;
};

export type JobEventRow = {
  /** Job event primary key. */
  id: string;
  /** Related video record id. */
  recordId: string;
  /** Owner user id from Supabase Auth. */
  userId: string;
  /** Status or processing phase represented by this event. */
  status: VideoRecordStatus;
  /** Human-readable status message, failure hint, or worker log summary. */
  message: string | null;
  /** Structured event metadata, such as provider, duration, or retry count. */
  metadata: Record<string, unknown>;
  /** Time when this event occurred. */
  createdAt: Date;
};

export type UsageEventRow = {
  /** Usage event primary key. */
  id: string;
  /** Owner user id from Supabase Auth. */
  userId: string;
  /** Related video record id. Null for usage events not tied to a single record. */
  recordId: string | null;
  /** Type of usage event being counted. */
  eventType: UsageEventType;
  /** Measured quantity for this event, such as 1 count or transcription minutes. */
  quantity: number;
  /** Unit for `quantity`, such as count or minute. */
  unit: UsageUnit;
  /** Time when this usage event occurred. */
  createdAt: Date;
};
